# builder stage
FROM node:25-alpine3.21 AS builder
WORKDIR /app

COPY package*.json tsconfig.json ./
COPY prisma ./prisma/
COPY deploy/docker/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh

RUN chmod +x /usr/local/bin/docker-entrypoint.sh
RUN npm ci
RUN npx prisma generate

COPY . .
RUN npm run build

STOPSIGNAL SIGTERM

ENV NODE_ENV=development
ENV COOKIE_SECURE=false
ENV LOG_LEVEL=debug
EXPOSE ${APP_PORT}

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
CMD ["npm", "run", "dev"]